[config]
# number of total word- and bitlines
name = "[32NNA68] PLCC 32×32 (SA)"
words = 32
bits = 32
mask = [
    [ 0,  0], [ 1, 30], [ 2,  2], [ 3, 28],
    [ 4,  4], [ 5, 26], [ 6,  6], [ 7, 24],
    [ 8,  8], [ 9, 22], [10, 10], [11, 20],
    [12, 12], [13, 18], [14, 14], [15, 16],
    [16, 15], [17, 17], [18, 13], [19, 19],
    [20, 11], [21, 21], [22,  9], [23, 23],
    [24,  7], [25, 25], [26,  5], [27, 27],
    [28,  3], [29, 29], [30,  1], [31, 31]
]

[ioconfs]

[ioconfs.internal]
name = "Socket"
ios = 0b0
dir = ["out", "out", "out", "out"]

[ioconfs.header]
name = "Header"
ios = 0b1
dir = ["out", "out", "out", "out"]


[mapping]
# corresponding channels for wordlines
words = [
    16, 63, 17, 62, 18, 61, 19, 60,
    20, 59, 21, 58, 22, 57, 23, 56,
    24, 55, 25, 54, 26, 53, 27, 52,
    28, 51, 29, 50, 30, 49, 31, 48
]

bits = [
    15, 32, 14, 33, 13, 34, 12, 35,
    11, 36, 10, 37,  9, 38,  8, 39,
     7, 40,  6, 41,  5, 42,  4, 43,
     3, 44,  2, 45,  1, 46,  0, 47
]
